// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Martin Krucinski on 28-Feb-2017 at 23:03
#define Hmin      59.4118
#define Hmax      79.6341
#define Smin     230.3846
#define Smax     255.0000
#define Lmin      26.3333
#define Lmax      67.6471
#define MinHeight      37.0000
#define MinWidth      10.0000
