// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This was written by Jacob Krucinski on 23-Feb-2017 at 19:17
#define Hmin      68.6364
#define Hmax      82.9562
#define Smin     162.7632
#define Smax     219.9057
#define Lmin      35.3529
#define Lmax      89.6078
#define Height      19.0000
#define Width       5.0000
#define MinHeight      18.0000
#define MinWidth       6.0000
