// THIS IS AUTOGENERATED CODE FOR VISION TARGETS WRITTEN IN MATLAB
// This file was auto-generated by Matlab under the supervision of Jacob Krucinski on 24-Mar-2017 at 18:12
#define Hmin      64.4054
#define Hmax      79.2105
#define Smin     226.3115
#define Smax     255.0000
#define Lmin      47.1176
#define Lmax      89.6078
#define MinHeight      25.0000
#define MinWidth       9.0000
