// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "CANTalon.h"

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<CANTalon> RobotMap::driveTrainCANTalonLeft;
std::shared_ptr<CANTalon> RobotMap::driveTrainCANTalonRight;
std::shared_ptr<RobotDrive> RobotMap::driveTrainRobotDrive;
std::shared_ptr<CANTalon> RobotMap::driveTrainCANTalonSlaveLeft;
std::shared_ptr<CANTalon> RobotMap::driveTrainCANTalonSlaveRight;
std::shared_ptr<Servo> RobotMap::payloadDoorServoA;
std::shared_ptr<Servo> RobotMap::payloadDoorServoB;
std::shared_ptr<CANTalon> RobotMap::payloadCANTalonElevator;
std::shared_ptr<CANTalon> RobotMap::payloadCANTalonClimber;
std::shared_ptr<SpeedController> RobotMap::payloadSpeedControllerIntake;
std::shared_ptr<DigitalInput> RobotMap::payloadLimitSwitchHome;
std::shared_ptr<SpeedController> RobotMap::dumperSpeedControllerDumper;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
std::shared_ptr<AHRS> RobotMap::driveTrainAHRS;

void RobotMap::init() {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LiveWindow *lw = LiveWindow::GetInstance();

    driveTrainCANTalonLeft.reset(new CANTalon(1));
    lw->AddActuator("Drive Train", "CAN Talon Left", driveTrainCANTalonLeft);
    
    driveTrainCANTalonRight.reset(new CANTalon(2));
    lw->AddActuator("Drive Train", "CAN Talon Right", driveTrainCANTalonRight);
    
    driveTrainRobotDrive.reset(new RobotDrive(driveTrainCANTalonLeft, driveTrainCANTalonRight));
    
    driveTrainRobotDrive->SetSafetyEnabled(false);
        driveTrainRobotDrive->SetExpiration(0.1);
        driveTrainRobotDrive->SetSensitivity(0.5);
        driveTrainRobotDrive->SetMaxOutput(1.0);

    driveTrainCANTalonSlaveLeft.reset(new CANTalon(3));
    lw->AddActuator("Drive Train", "CAN Talon Slave Left", driveTrainCANTalonSlaveLeft);
    
    driveTrainCANTalonSlaveRight.reset(new CANTalon(4));
    lw->AddActuator("Drive Train", "CAN Talon Slave Right", driveTrainCANTalonSlaveRight);
    
    payloadDoorServoA.reset(new Servo(0));
    lw->AddActuator("Payload", "DoorServo A", payloadDoorServoA);
    
    payloadDoorServoB.reset(new Servo(2));
    lw->AddActuator("Payload", "Door Servo B", payloadDoorServoB);
    
    payloadCANTalonElevator.reset(new CANTalon(5));
    lw->AddActuator("Payload", "CAN Talon Elevator", payloadCANTalonElevator);
    
    payloadCANTalonClimber.reset(new CANTalon(6));
    lw->AddActuator("Payload", "CAN Talon Climber", payloadCANTalonClimber);
    
    payloadSpeedControllerIntake.reset(new Victor(1));
    lw->AddActuator("Payload", "Speed Controller Intake", std::static_pointer_cast<Victor>(payloadSpeedControllerIntake));
    
    payloadLimitSwitchHome.reset(new DigitalInput(0));
    lw->AddSensor("Payload", "Limit Switch Home", payloadLimitSwitchHome);
    
    dumperSpeedControllerDumper.reset(new Victor(3));
    lw->AddActuator("Dumper", "Speed Controller Dumper", std::static_pointer_cast<Victor>(dumperSpeedControllerDumper));
    


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
//    driveTrainAHRS.reset(new AHRS(SerialPort::Port::kUSB));
}
