// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousAllianceCmd.h"

AutonomousAllianceCmd::AutonomousAllianceCmd() :
		ConditionalCommand(new frc::PrintCommand("Red"),
				new frc::PrintCommand("Blue")) {

}

bool AutonomousAllianceCmd::Condition(){
	//Return true if Red, false otherwise (i.e. Blue)
	return (frc::DriverStation::GetInstance().GetAlliance()
			== frc::DriverStation::kRed);
}

AutonomousAllianceCmd::AutonomousAllianceCmd(Command* onRed, Command* onBlue) :
		ConditionalCommand(onRed, onBlue) {
}
