// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef AUTONOMOUS_VELOCITY_PROFILE_H
#define AUTONOMOUS_VELOCITY_PROFILE_H


#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "../ProfileData.h"


/**
 *
 *
 * @author ExampleAuthor
 */
class AutonomousVelocityProfile: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutonomousVelocityProfile();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	AutonomousVelocityProfile(const ProfileData* LeftWheel, const ProfileData* RightWheel,
			double time = 0.0, int* error = nullptr);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLES
	std::shared_ptr<const ProfileData> mLeftWheel;	// Pointer to left side motion profile data
	std::shared_ptr<const ProfileData> mRightWheel;	// Pointer to right side motion profile data

	unsigned int mCount;
	int* mErrorSource;
	const double kPGain;
	double mTime;

	unsigned int GetVelocityOffset(void);
	frc::Timer VelocityTimer;
};

#endif
