// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "AutonomousMotionProfile.h"
#include <iostream>
#include <fstream>
#include <string>

int AutonomousMotionProfile::Notifier_counter;

//counter to 0, notifier increase, is finish, search for counter to be greater than one
AutonomousMotionProfile::AutonomousMotionProfile(): Command(),
	talonService(AutonomousMotionProfile::PeriodicTask) {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	AutonomousMotionProfile::Notifier_counter = 0;
}


// Called just before this Command runs the first time
void AutonomousMotionProfile::Initialize() {
	Robot::driveTrain->SetChassisMode(CANTalon::TalonControlMode::kMotionProfileMode);
	AutonomousMotionProfile::Notifier_counter = 0;
	if (bResetGyro) {
		Robot::driveTrain->ResetChassisYaw();
	}

	if (mRightWheel) {
		Robot::driveTrain->FillProfileBuffer(mLeftWheel, mRightWheel);
	}
	else {
		Robot::driveTrain->FillProfileBuffer(mLeftWheel);
	}
	double ServiceRate = mLeftWheel->at(0).at(2);
	talonService.StartPeriodic(ServiceRate / 2000.0);	// 1/2 rate of motion profile
}

// Called repeatedly when this Command is scheduled to run
void AutonomousMotionProfile::Execute() {
	Robot::driveTrain->TelemetryUpdate();
}

// Make this return true when this Command no longer needs to run execute()
bool AutonomousMotionProfile::IsFinished() {
    if(AutonomousMotionProfile::Notifier_counter > 20)
    {
    	  return Robot::driveTrain->MotionProfileComplete();
    }
    else
    {
    	return false;
    }
}

// Called once after isFinished returns true
void AutonomousMotionProfile::End() {
	talonService.Stop();
	if (!bBlended) {
		Robot::driveTrain->SetMotionProfileState(
				CANTalon::SetValueMotionProfile::SetValueMotionProfileHold);
		Robot::driveTrain->SetChassisMode(CANTalon::TalonControlMode::kThrottleMode);
	}
	else {
		Robot::driveTrain->SetMotionProfileState(
				CANTalon::SetValueMotionProfile::SetValueMotionProfileDisable);
	}
}


// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void AutonomousMotionProfile::Interrupted() {
	End();
}

AutonomousMotionProfile::AutonomousMotionProfile(const ProfileData* LeftWheel, bool ResetGyro) : Command(),
		talonService(AutonomousMotionProfile::PeriodicTask){
	Requires(Robot::driveTrain.get());
	bResetGyro = ResetGyro;
	mLeftWheel.reset(LeftWheel);
	mRightWheel.reset();
}

AutonomousMotionProfile::AutonomousMotionProfile(const ProfileData* LeftWheel,
		const ProfileData* RightWheel, bool ResetGyro, bool Blended, double time) : Command(),
				talonService(AutonomousMotionProfile::PeriodicTask) {
	Requires(Robot::driveTrain.get());
	int Count;
	bResetGyro = ResetGyro;
	bBlended = Blended;
	mLeftWheel.reset(LeftWheel);
	mRightWheel.reset(RightWheel);
	Count = (int)(time / (mLeftWheel->at(0).at(2) / 1000));
	for(int j = 0; j < Count; j++) {
		mLocalLeftWheel.push_back(mLeftWheel->at(j));
	}
	mTime = time;
}

AutonomousMotionProfile::AutonomousMotionProfile(
		const std::string& LProfileName, const std::string& RProfileName, bool ResetGyro) :
		Command(), talonService(AutonomousMotionProfile::PeriodicTask) {

	Requires(Robot::driveTrain.get());

	bResetGyro = ResetGyro;
	std::ifstream input(LProfileName.c_str());
	std::string token;
	std::array<double, 3> rowData;

	mLeftProfile.clear();
	mRightProfile.clear();

	mLeftWheel.reset(&mLeftProfile);
	mRightWheel.reset(&mRightProfile);

	while (input.good()) {
		std::getline(input, token, ',');
		rowData[0] = std::stod(token);
		std::getline(input, token, ',');
		rowData[1] = std::stod(token);
		std::getline(input, token, ',');
		rowData[2] = std::stod(token);

		std::getline(input,token);
		mLeftProfile.push_back(rowData);
	}

	printf("%s loaded %u points\n",
			LProfileName.c_str(), mLeftProfile.size());

	input.close();
	input.open(RProfileName.c_str());

	while (input.good()) {
		std::getline(input, token, ',');
		rowData[0] = std::stod(token);
		std::getline(input, token, ',');
		rowData[1] = std::stod(token);
		std::getline(input, token, ',');
		rowData[2] = std::stod(token);

		std::getline(input,token);
		mRightProfile.push_back(rowData);
	}

	printf("%s loaded %u points\n",
			RProfileName.c_str(), mRightProfile.size());
}


void AutonomousMotionProfile::PeriodicTask() {
	Robot::driveTrain->ServiceMotionProfile();
	Notifier_counter++;
}

AutonomousMotionProfile::AutonomousMotionProfile(
		const std::string& ProfileName, bool ResetGyro) : Command(),
				talonService(AutonomousMotionProfile::PeriodicTask) {

	Requires(Robot::driveTrain.get());

	bResetGyro = ResetGyro;
	std::ifstream input(ProfileName.c_str());
	std::string token;
	std::array<double, 3> rowData;

	mLeftProfile.clear();
	mRightProfile.clear();

	mLeftWheel.reset(&mLeftProfile);
	mRightWheel.reset();

	while (input.good()) {
		std::getline(input, token, ',');
		rowData[0] = std::stod(token);
		std::getline(input, token, ',');
		rowData[1] = std::stod(token);
		std::getline(input, token, ',');
		rowData[2] = std::stod(token);

		//this line is to make sure to get rid of the \r
		std::getline(input,token);
		mLeftProfile.push_back(rowData);
	}

	printf("%s loaded %u points\n",
			ProfileName.c_str(), mLeftProfile.size());
}
