
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#ifndef AUTONOMOUS_ALLIANCE_CMD_H
#define AUTONOMOUS_ALLIANCE_CMD_H
#include "Commands/ConditionalCommand.h"


#include "Commands/PrintCommand.h"
#include <DriverStation.h>

class AutonomousAllianceCmd : public ConditionalCommand {
public:
	AutonomousAllianceCmd();
	AutonomousAllianceCmd(Command* onRed, Command* onBlue);
protected:
virtual bool Condition();
};

#endif
