// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "TankDriveTeleop.h"
#include <iostream>


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

TankDriveTeleop::TankDriveTeleop(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::driveTrain.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void TankDriveTeleop::Initialize() {
	mDriverControl = new Xbox360(Robot::oi->getLeftDriverJoystick());
}

// Called repeatedly when this Command is scheduled to run
void TankDriveTeleop::Execute() {
	// Gather the XBox controller left and right joystick Y axes values from the most recently received
	// Driver Station transmission packet, and send them to the chassis TankDriveWithTriggers method
	double left = mDriverControl->GetLeftY();
	double right = mDriverControl->GetRightY();

	Robot::driveTrain->TankDriveWithTriggers(left, right, mDriverControl->GetTriggers());
}

// Make this return true when this Command no longer needs to run execute()
bool TankDriveTeleop::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void TankDriveTeleop::End() {

}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void TankDriveTeleop::Interrupted() {
	End();
}
